<?php

/**
 * This is the model base class for the table "gallery_image".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GalleryImage".
 *
 * Columns in table "gallery_image" available as properties of the model,
 * followed by relations of table "gallery_image" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_category
 * @property string $image
 * @property string $description
 *
 * @property GalleryCategory $idCategory
 */
abstract class BaseGalleryImage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gallery_image';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GalleryImage|GalleryImages', $n);
	}

	public static function representingColumn() {
		return 'image';
	}

	public function rules() {
		return array(
			array('id_category, image', 'required'),
			array('id_category', 'numerical', 'integerOnly'=>true),
			array('image', 'length', 'max'=>1024),
			array('description', 'length', 'max'=>255),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_category, image, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCategory' => array(self::BELONGS_TO, 'GalleryCategory', 'id_category'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_category' => null,
			'image' => Yii::t('app', 'Image'),
			'description' => Yii::t('app', 'Description'),
			'idCategory' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_category', $this->id_category);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}