<?php

/**
 * This is the model base class for the table "our_team".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OurTeam".
 *
 * Columns in table "our_team" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $image
 * @property string $first_name
 * @property string $last_name
 * @property string $position
 * @property string $phone_number
 * @property string $mobile_number
 * @property string $fax_number
 * @property string $email
 * @property string $website
 * @property string $address
 * @property string $facebook
 * @property string $twitter
 * @property integer $is_active
 *
 */
abstract class BaseOurTeam extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'our_team';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OurTeam|OurTeams', $n);
	}

	public static function representingColumn() {
		return 'first_name';
	}

	public function rules() {
		return array(
			array('first_name, last_name, image', 'required'),
			array('is_active', 'numerical', 'integerOnly'=>true),
			array('image', 'length', 'max'=>255),
			array('first_name, last_name, position, email, website, address, facebook, twitter', 'length', 'max'=>45),
			array('phone_number, mobile_number, fax_number', 'length', 'max'=>30),
			array('image, position, phone_number, mobile_number, fax_number, email, website, address, facebook, twitter, is_active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, image, first_name, last_name, position, phone_number, mobile_number, fax_number, email, website, address, facebook, twitter, is_active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'image' => Yii::t('app', 'Image'),
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'position' => Yii::t('app', 'Position'),
			'phone_number' => Yii::t('app', 'Phone Number'),
			'mobile_number' => Yii::t('app', 'Mobile Number'),
			'fax_number' => Yii::t('app', 'Fax Number'),
			'email' => Yii::t('app', 'Email'),
			'website' => Yii::t('app', 'Website'),
			'address' => Yii::t('app', 'Address'),
			'facebook' => Yii::t('app', 'Facebook'),
			'twitter' => Yii::t('app', 'Twitter'),
			'is_active' => Yii::t('app', 'Is Active'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('position', $this->position, true);
		$criteria->compare('phone_number', $this->phone_number, true);
		$criteria->compare('mobile_number', $this->mobile_number, true);
		$criteria->compare('fax_number', $this->fax_number, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('website', $this->website, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('facebook', $this->facebook, true);
		$criteria->compare('twitter', $this->twitter, true);
		$criteria->compare('is_active', $this->is_active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}